# ~/.tmuxinator/dev.yml

name: dev
root: ~/dev/html-client

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - editor:
      layout: 2329,315x74,0,0{247x74,0,0,15,67x74,248,0[67x57,248,0,16,67x16,248,58,17]}
      panes:
        - vim
        - #empty
        - grunt dev-nr --proxy staging
  - alt: #empty
